spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rupia-customer-db
    username:
    password:
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-id-address: true

#API base url for Micro services
services:
  rupia-auth-service:
    base-url: http://rupia-auth-service
  rupia-wallet-service:
    base-url: http://rupia-wallet-service
  rupia-transaction-service:
    base-url: http://rupia-transaction-service